version: "3.3"
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: docs
      MYSQL_USER: docs_user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - docker-backend-pdf-creator
  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"
    networks:
      - docker-backend-pdf-creator
  php-apache:
    build:
      context: .
      dockerfile: ./docker/php-apache/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
      - "9001:9001"
    volumes:
      - .:/var/www/html
      - ./docker/php-apache/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php-apache/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    environment:
      - APP_KEY=SomeRandomStringToAddSecurity123
      - APP_ENV=development
      - APP_DEBUG=true
      - PHP_IDE_CONFIG=serverName=nette_freelancer-portal
      - XDEBUG_MODE = DEBUG
    networks:
      - docker-backend-pdf-creator
networks:
  docker-backend-pdf-creator:
    driver: bridge